apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
  labels:
    app: flask
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  selector:
    app: flask